// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: izpLuD9XfjEg4waoVkj7iA
// Component: AYdZ6jQDwYWu6U
import * as React from 'react';

import * as p from '@plasmicapp/react-web';
import * as ph from '@plasmicapp/host';

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from '@plasmicapp/react-web';

import '@plasmicapp/react-web/lib/plasmic.css';

import plasmic_library_plasmic_color_type_css from '../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css'; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from './plasmic_furn_e_commerce.module.css'; // plasmic-import: izpLuD9XfjEg4waoVkj7iA/projectcss
import sty from './PlasmicRatings.module.css'; // plasmic-import: AYdZ6jQDwYWu6U/css

import StarIcon from './icons/PlasmicIcon__Star'; // plasmic-import: -5MG9_UBI3MwK/icon

export type PlasmicRatings__VariantMembers = {
  stars: 'zero' | 'one' | 'two' | 'three' | 'four' | 'five';
};

export type PlasmicRatings__VariantsArgs = {
  stars?: SingleChoiceArg<'zero' | 'one' | 'two' | 'three' | 'four' | 'five'>;
};

type VariantPropType = keyof PlasmicRatings__VariantsArgs;
export const PlasmicRatings__VariantProps = new Array<VariantPropType>('stars');

export type PlasmicRatings__ArgsType = {
  numReviews?: React.ReactNode;
};

type ArgPropType = keyof PlasmicRatings__ArgsType;
export const PlasmicRatings__ArgProps = new Array<ArgPropType>('numReviews');

export type PlasmicRatings__OverridesType = {
  root?: p.Flex<'div'>;
  freeBox?: p.Flex<'div'>;
};

export interface DefaultRatingsProps {
  numReviews?: React.ReactNode;
  stars?: SingleChoiceArg<'zero' | 'one' | 'two' | 'three' | 'four' | 'five'>;
  className?: string;
}

function PlasmicRatings__RenderFunc(props: {
  variants: PlasmicRatings__VariantsArgs;
  args: PlasmicRatings__ArgsType;
  overrides: PlasmicRatings__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <p.Stack
      as={'div'}
      data-plasmic-name={'root'}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_tokens,
        plasmic_library_plasmic_color_type_css.plasmic_tokens,
        sty.root,
        {
          [sty.rootstars_five]: hasVariant(variants, 'stars', 'five'),
          [sty.rootstars_four]: hasVariant(variants, 'stars', 'four'),
          [sty.rootstars_one]: hasVariant(variants, 'stars', 'one'),
          [sty.rootstars_three]: hasVariant(variants, 'stars', 'three'),
          [sty.rootstars_two]: hasVariant(variants, 'stars', 'two'),
          [sty.rootstars_zero]: hasVariant(variants, 'stars', 'zero'),
        }
      )}
    >
      <p.Stack
        as={'div'}
        data-plasmic-name={'freeBox'}
        data-plasmic-override={overrides.freeBox}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        {(hasVariant(variants, 'stars', 'zero') ? true : true) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__gCnNq, {
              [sty.svgstars_five__gCnNQtZtLw]: hasVariant(
                variants,
                'stars',
                'five'
              ),
              [sty.svgstars_zero__gCnNQf65F1]: hasVariant(
                variants,
                'stars',
                'zero'
              ),
            })}
            role={'img'}
          />
        ) : null}
        {(
          hasVariant(variants, 'stars', 'five')
            ? true
            : hasVariant(variants, 'stars', 'four')
            ? true
            : hasVariant(variants, 'stars', 'three')
            ? true
            : hasVariant(variants, 'stars', 'two')
            ? true
            : hasVariant(variants, 'stars', 'one')
            ? true
            : hasVariant(variants, 'stars', 'zero')
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg___0DqD1, {
              [sty.svgstars_five___0DqD1TZtLw]: hasVariant(
                variants,
                'stars',
                'five'
              ),
              [sty.svgstars_four___0DqD1K9QdU]: hasVariant(
                variants,
                'stars',
                'four'
              ),
              [sty.svgstars_one___0DqD1BtaaK]: hasVariant(
                variants,
                'stars',
                'one'
              ),
              [sty.svgstars_three___0DqD1GSxm]: hasVariant(
                variants,
                'stars',
                'three'
              ),
              [sty.svgstars_two___0DqD1Tcklh]: hasVariant(
                variants,
                'stars',
                'two'
              ),
              [sty.svgstars_zero___0DqD1F65F1]: hasVariant(
                variants,
                'stars',
                'zero'
              ),
            })}
            role={'img'}
          />
        ) : null}
        {(
          hasVariant(variants, 'stars', 'five')
            ? true
            : hasVariant(variants, 'stars', 'four')
            ? true
            : hasVariant(variants, 'stars', 'three')
            ? true
            : hasVariant(variants, 'stars', 'two')
            ? true
            : hasVariant(variants, 'stars', 'one')
            ? true
            : hasVariant(variants, 'stars', 'zero')
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__ip9Ei, {
              [sty.svgstars_five__ip9EitZtLw]: hasVariant(
                variants,
                'stars',
                'five'
              ),
              [sty.svgstars_four__ip9Eik9QdU]: hasVariant(
                variants,
                'stars',
                'four'
              ),
              [sty.svgstars_one__ip9EibtaaK]: hasVariant(
                variants,
                'stars',
                'one'
              ),
              [sty.svgstars_three__ip9EiGSxm]: hasVariant(
                variants,
                'stars',
                'three'
              ),
              [sty.svgstars_two__ip9EiTcklh]: hasVariant(
                variants,
                'stars',
                'two'
              ),
              [sty.svgstars_zero__ip9Eif65F1]: hasVariant(
                variants,
                'stars',
                'zero'
              ),
            })}
            role={'img'}
          />
        ) : null}
        {(
          hasVariant(variants, 'stars', 'five')
            ? true
            : hasVariant(variants, 'stars', 'four')
            ? true
            : hasVariant(variants, 'stars', 'three')
            ? true
            : hasVariant(variants, 'stars', 'two')
            ? true
            : hasVariant(variants, 'stars', 'one')
            ? true
            : hasVariant(variants, 'stars', 'zero')
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__twUxF, {
              [sty.svgstars_five__twUxFtZtLw]: hasVariant(
                variants,
                'stars',
                'five'
              ),
              [sty.svgstars_four__twUxFk9QdU]: hasVariant(
                variants,
                'stars',
                'four'
              ),
              [sty.svgstars_one__twUxFbtaaK]: hasVariant(
                variants,
                'stars',
                'one'
              ),
              [sty.svgstars_three__twUxFGSxm]: hasVariant(
                variants,
                'stars',
                'three'
              ),
              [sty.svgstars_two__twUxFTcklh]: hasVariant(
                variants,
                'stars',
                'two'
              ),
              [sty.svgstars_zero__twUxFf65F1]: hasVariant(
                variants,
                'stars',
                'zero'
              ),
            })}
            role={'img'}
          />
        ) : null}
        {(
          hasVariant(variants, 'stars', 'five')
            ? true
            : hasVariant(variants, 'stars', 'four')
            ? true
            : hasVariant(variants, 'stars', 'three')
            ? true
            : hasVariant(variants, 'stars', 'two')
            ? true
            : hasVariant(variants, 'stars', 'one')
            ? true
            : hasVariant(variants, 'stars', 'zero')
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__zxikp, {
              [sty.svgstars_five__zxikptZtLw]: hasVariant(
                variants,
                'stars',
                'five'
              ),
              [sty.svgstars_four__zxikpk9QdU]: hasVariant(
                variants,
                'stars',
                'four'
              ),
              [sty.svgstars_one__zxikpbtaaK]: hasVariant(
                variants,
                'stars',
                'one'
              ),
              [sty.svgstars_three__zxikpGSxm]: hasVariant(
                variants,
                'stars',
                'three'
              ),
              [sty.svgstars_two__zxikpTcklh]: hasVariant(
                variants,
                'stars',
                'two'
              ),
              [sty.svgstars_zero__zxikpf65F1]: hasVariant(
                variants,
                'stars',
                'zero'
              ),
            })}
            role={'img'}
          />
        ) : null}
        {(
          hasVariant(variants, 'stars', 'five')
            ? true
            : hasVariant(variants, 'stars', 'four')
            ? true
            : hasVariant(variants, 'stars', 'three')
            ? true
            : hasVariant(variants, 'stars', 'two')
            ? true
            : hasVariant(variants, 'stars', 'one')
            ? true
            : hasVariant(variants, 'stars', 'zero')
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__ywX3J, {
              [sty.svgstars_five__ywX3JtZtLw]: hasVariant(
                variants,
                'stars',
                'five'
              ),
              [sty.svgstars_four__ywX3Jk9QdU]: hasVariant(
                variants,
                'stars',
                'four'
              ),
              [sty.svgstars_one__ywX3JbtaaK]: hasVariant(
                variants,
                'stars',
                'one'
              ),
              [sty.svgstars_three__ywX3JGSxm]: hasVariant(
                variants,
                'stars',
                'three'
              ),
              [sty.svgstars_two__ywX3JTcklh]: hasVariant(
                variants,
                'stars',
                'two'
              ),
              [sty.svgstars_zero__ywX3Jf65F1]: hasVariant(
                variants,
                'stars',
                'zero'
              ),
            })}
            role={'img'}
          />
        ) : null}
        {(
          hasVariant(variants, 'stars', 'five')
            ? true
            : hasVariant(variants, 'stars', 'four')
            ? true
            : hasVariant(variants, 'stars', 'three')
            ? true
            : hasVariant(variants, 'stars', 'two')
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__oair7, {
              [sty.svgstars_five__oair7TZtLw]: hasVariant(
                variants,
                'stars',
                'five'
              ),
              [sty.svgstars_four__oair7K9QdU]: hasVariant(
                variants,
                'stars',
                'four'
              ),
              [sty.svgstars_three__oair7GSxm]: hasVariant(
                variants,
                'stars',
                'three'
              ),
              [sty.svgstars_two__oair7Tcklh]: hasVariant(
                variants,
                'stars',
                'two'
              ),
            })}
            role={'img'}
          />
        ) : null}
        {(
          hasVariant(variants, 'stars', 'five')
            ? true
            : hasVariant(variants, 'stars', 'four')
            ? true
            : hasVariant(variants, 'stars', 'three')
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg___99Tsp, {
              [sty.svgstars_five___99TsPtZtLw]: hasVariant(
                variants,
                'stars',
                'five'
              ),
              [sty.svgstars_four___99TsPk9QdU]: hasVariant(
                variants,
                'stars',
                'four'
              ),
              [sty.svgstars_three___99TspGSxm]: hasVariant(
                variants,
                'stars',
                'three'
              ),
            })}
            role={'img'}
          />
        ) : null}
        {(
          hasVariant(variants, 'stars', 'five')
            ? true
            : hasVariant(variants, 'stars', 'four')
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__nqke2, {
              [sty.svgstars_five__nqke2TZtLw]: hasVariant(
                variants,
                'stars',
                'five'
              ),
              [sty.svgstars_four__nqke2K9QdU]: hasVariant(
                variants,
                'stars',
                'four'
              ),
            })}
            role={'img'}
          />
        ) : null}
        {(hasVariant(variants, 'stars', 'five') ? true : true) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__o6Ls2, {
              [sty.svgstars_five__o6Ls2TZtLw]: hasVariant(
                variants,
                'stars',
                'five'
              ),
            })}
            role={'img'}
          />
        ) : null}
      </p.Stack>

      {p.renderPlasmicSlot({
        defaultContents: '(45 Review)',
        value: args.numReviews,
        className: classNames(sty.slotTargetNumReviews),
      })}
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ['root', 'freeBox'],
  freeBox: ['freeBox'],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: 'div';
  freeBox: 'div';
};

type ReservedPropsType = 'variants' | 'args' | 'overrides';
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRatings__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRatings__VariantsArgs;
    args?: PlasmicRatings__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicRatings__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicRatings__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRatings__ArgProps,
      internalVariantPropNames: PlasmicRatings__VariantProps,
    });

    return PlasmicRatings__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === 'root') {
    func.displayName = 'PlasmicRatings';
  } else {
    func.displayName = `PlasmicRatings.${nodeName}`;
  }
  return func;
}

export const PlasmicRatings = Object.assign(
  // Top-level PlasmicRatings renders the root element
  makeNodeComponent('root'),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent('freeBox'),

    // Metadata about props expected for PlasmicRatings
    internalVariantProps: PlasmicRatings__VariantProps,
    internalArgProps: PlasmicRatings__ArgProps,
  }
);

export default PlasmicRatings;
/* prettier-ignore-end */
